### ISSUE TITLE
Missing real example

### ISSUE THREAD

**Issue by deeplook** [jsignell/dask-geopandas#12]
I'm trying to evaluate this package by writing a little example, but I'm running into some errors below. I try to write a small small example, to read a [simple CSV file](https://github.com/IzabelaSmiech/airports/blob/master/airport_volume_airport_locations.csv) with lat/lon columns, add a geometry column and turn this into a Dask-GeoDateFrame, but I'm running into errors like these:

- `AttributeError: 'Series' object has no attribute 'map_partitions'`
- `AttributeError: 'DataFrame' object has no attribute 'geometry'` 

```python
import dask_geopandas
import dask.dataframe as dd
import pandas as pd
import geopandas as gd

df = pd.read_csv('airport_volume_airport_locations.csv')

# ok
gdf = gd.GeoDataFrame(
    df, geometry=gd.points_from_xy(df.Airport1Latitude, df.Airport1Longitude)
)

ddf = dask_geopandas.from_geopandas(df, npartitions=4)
# raises AttributeError: 'DataFrame' object has no attribute 'set_geometry'
ddf.set_geometry(
    dask_geopandas.points_from_xy(ddf, "Airport1Latitude", "Airport1Longitude")
)
```

**Comment by jorisvandenbossche** [comment]
@deeplook thanks for taking a look and giving feedback! (and yes, examples are still very scarce ..)

The `dask_geopandas.from_geopandas` expects a GeoDataFrame, but you are passing it a DataFrame (`df`, and not `gdf`). We should probably already check that and directly raise an error, instead of letting it result in an error in a later operation.

For what you are trying to do (create a dask_geopandas.GeoDataFrame from a dask.DataFrame (and not from a geopandas.GeoDataFrame)), you can do something like:

```
ddf = dd.from_pandas(df, npartitions=4)
ddf["geometry"] = dask_geopandas.points_from_xy(ddf, "Airport1Latitude", "Airport1Longitude")
gddf = dask_geopandas.from_dask_dataframe(ddf)
```

The reason is that this is a bit more complicated than the `set_geometry` which you tried (and works for plain GeoPandas), is because GeoPandas monkey-patches the pandas DataFrame with a `set_geometry` method so that you can convert a pandas DataFrame which already has a geometry column to a GeoDataFrame using that method. 
But we didn't (yet) do the same in dask_geopandas (we probably could for consistency with geopandas).

**Comment by deeplook** [comment]
Thanks! I'll surely come back with other things... ;)
